// <auto-generated />
namespace FurkanBelikirikSmartProFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Kitap_Kullanici : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kitap_Kullanici));
        
        string IMigrationMetadata.Id
        {
            get { return "202407052033334_Kitap_Kullanici"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
